FROM node:20-alpine AS build

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

ARG VITE_NOCODB_TOKEN
ARG VITE_NOCODB_BASE_URL
ARG VITE_NOCODB_SOURCE_ID
ARG VITE_NOCODB_BASE_ID
ARG VITE_NOCODB_TABLE_ID

ENV VITE_NOCODB_TOKEN=$VITE_NOCODB_TOKEN
ENV VITE_NOCODB_BASE_URL=$VITE_NOCODB_BASE_URL
ENV VITE_NOCODB_SOURCE_ID=$VITE_NOCODB_SOURCE_ID
ENV VITE_NOCODB_BASE_ID=$VITE_NOCODB_BASE_ID
ENV VITE_NOCODB_TABLE_ID=$VITE_NOCODB_TABLE_ID

RUN npm run build

FROM node:20-alpine AS runtime

WORKDIR /app

RUN npm install -g serve

COPY --from=build /app/dist ./dist

EXPOSE 3000

CMD ["serve", "-s", "dist", "-l", "3000"]
